require:
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 100

Metrics/PerceivedComplexity:
  Enabled: false
